DROP USER IF EXISTS projetDML;
CREATE USER projetDML IDENTIFIED BY 'dM#gmvmUcg9FE5n5';
GRANT USAGE ON projet.* TO 'projetDML';
GRANT SELECT,UPDATE,DELETE,INSERT,EXECUTE ON projet.* TO 'projetDML';

DROP USER IF EXISTS projetDDL;
CREATE USER projetDDL IDENTIFIED BY 'tGWk_nEpRdn#k4t8';
GRANT ALL ON projet.* TO 'projetDDL';